exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://eyoy.github.io/mmsynergy"
  
title: Jekyll Theme Primer
description: Primer is a Jekyll theme for GitHub Pages
