exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://eyoy.github.io/mmsynergy"
  
title: Music Motion Synergy
description: GitHub Pages for the Music Motion Synergy Project
